# LOG CONFIGURATION
spring.main.banner-mode=off
logging.pattern.console=%d{yyyy-MM-dd-HH:mm:ss.SSS} [%-5level] %logger - %msg%n
logging.level.root=WARN
logging.level.cherry=DEBUG
logging.level.org.springframework=INFO

# TRACE CONFIGURATION
trace.useDynamicLogger=true
trace.hideProxyClassNames=true
trace.logExceptionStackTrace=true
trace.enterMessage=ENTER $[targetClassShortName]#$[methodName]($[arguments])
trace.exitMessage=EXIT  $[targetClassShortName]#$[methodName](): $[returnValue]
trace.exceptionMessage=EXCEPTION $[targetClassShortName]#$[methodName](): $[exception]
