# LOG CONFIGURATION
logging.pattern.console=%d{yyyy-MM-dd-HH:mm:ss.SSS} [%-5level] %logger - %msg%X{querydsl.parameters}%n
logging.level.root=WARN
logging.level.cherry=TRACE
logging.level.com.querydsl=DEBUG
logging.level.org.springframework=INFO
